language: python
python:
  - 2.7
  - 3.2
  - 3.4
  - 3.5
  - pypy
  - nightly

matrix:
  allow_failures:
    - python: nightly

install:
  - 'python setup.py install'
  - 'pip install nose'

script: 'nosetests'